name: Scheduled Job

on:
  push:
  schedule:
    - cron: '*/5 * * * *'  # 每天午夜执行

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, World!
