name: Scheduled Job

on:
  schedule:
    - cron: '*/6 * * * *'
env:
  TZ: Asia/Shanghai

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Hello, World!
